server:
  port: 8084

spring:
  application:
    name: delivery-service
  data:
    mongodb:
      uri: ${MONGODB_URI_DELIVERY}
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: delivery-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

kafka:
  topic:
    order-created: smarteats.order.created
    order-accepted: smarteats.order.accepted
    delivery-assigned: smarteats.delivery.assigned
    order-delivered: smarteats.order.delivered
    driver-registered: smarteats.auth.driver-registered
    status-updated: smarteats.auth.status-updated

services:
  restaurant-service:
    url: ${SERVICES_RESTAURANT_SERVICE_URL:http://localhost:8082}
