server:
  port: 8085

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: ${MONGODB_URI_NOTIFICATION}
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  topic:
    order-created: smarteats.order.created
    delivery-assigned: smarteats.delivery.assigned
    order-delivered: smarteats.order.delivered
    order-ready: smarteats.order.ready
    delivery-offer: smarteats.delivery.offer

services:
  delivery-service:
    url: ${DELIVERY_SERVICE_URL:http://localhost:8084}
  restaurant-service:
    url: ${SERVICES_RESTAURANT_SERVICE_URL:http://localhost:8082}
