version: '3.8'

services:
  # Primary Database
  mongodb:
    image: mongo:latest
    container_name: smarteats-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - smarteats-network
    restart: always

  # MongoDB GUI Client
  mongo-express:
    image: mongo-express:latest
    container_name: smarteats-mongo-express
    depends_on:
      - mongodb
    ports:
      - "8088:8081" # Exposed on 8088 to prevent port conflict with auth-service (8081)
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    networks:
      - smarteats-network
    restart: always

  # In-Memory Cache & Cart Store
  redis:
    image: redis:alpine
    container_name: smarteats-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - smarteats-network
    restart: always

  # Event-Driven Messaging Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: smarteats-rabbitmq
    ports:
      - "5672:5672"     # AMQP transport port
      - "15672:15672"   # Management Web UI Console
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - smarteats-network
    restart: always

volumes:
  mongo-data:
  redis-data:

networks:
  smarteats-network:
    driver: bridge
