server:
  port: 8081

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: ${MONGODB_URI_AUTH}
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topic:
    restaurant-registered: smarteats.auth.restaurant-registered
    driver-registered: smarteats.auth.driver-registered
    ngo-registered: smarteats.auth.ngo-registered
    status-updated: smarteats.auth.status-updated

# JWT Configuration
jwt:
  # Base64-encoded key (at least 256 bits). Under production, this must be loaded from env/secrets.
  secret: ${JWT_SECRET:dGhpcy1pcy1hLXNlY3JldC1rZXktZm9yLXNtYXJ0ZWF0cy1iYWNrZW5kLXByb2plY3QtbWNhLWRpc3NlcnRhdGlvbg==}
  expiration: 86400000 # 24 Hours in milliseconds
