server:
  port: 8082

spring:
  application:
    name: restaurant-service
  data:
    mongodb:
      uri: ${MONGODB_URI_RESTAURANT}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id: restaurant-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  cache:
    type: redis
    redis:
      time-to-live: 600000 # Cache TTL set to 10 minutes in milliseconds
      cache-null-values: false
